### ISSUE TITLE
a minor directory typo

### ISSUE THREAD

**Issue by zhihaozheng** [YuelongWu/feabas#5]
Regardless of configs, the directory of image driver always calls `mip0`
https://github.com/YuelongWu/feabas/blob/47d85335fb0bff02bb87099c862ab66c8040aa38/scripts/stitch_main.py#L275

but rendering in align_main asks for a `'mip'+str(mip_level)` directory
https://github.com/YuelongWu/feabas/blob/47d85335fb0bff02bb87099c862ab66c8040aa38/scripts/align_main.py#L230C8-L230C72

**Comment by YuelongWu** [comment]
My initial design was to always render the stitched images at mip0, and then generate the other mip-levels from the thumbnail downsampling process, which the alignment render code can use. I'm still figuring out the best way to allow rendering the stitched images at lower resolution. One thing I might do is to only introduce the concept of mip-levels after the stitched sections are rendered (and whatever resolution it is rendered at will be considered as "mip0"). In that way, the resolution of the aligned volume will always be no higher than the stitched section; and it also allows the raw data to have different resolutions for different sections. Will follow up with future updates.

**Comment by YuelongWu** [comment]
I committed a change regarding this issue. Now the logic goes like this:
1. The stitching rendering is now defined by the rendering [resolution](https://github.com/YuelongWu/feabas/blob/1ee3208d7eb6d2c4a32f641135a70b6d64aa1edf/configs/default_stitching_configs.yaml#L59C5-L59C21), rather than a scale. This accommodates scenarios where raw data has varying resolutions between sections. The current strategy will homogenize the resolution at the stitching rendering step, and this resolution will be the new mip0 going forwards.
2. If the resolution is not provided in the config file (setting to null), then the rendering step will sample the first a few stitching coordinate files, and use the mode of the [resolutions](https://github.com/YuelongWu/feabas/blob/1ee3208d7eb6d2c4a32f641135a70b6d64aa1edf/README.md?plain=1#L53) from the coordinate files as the rendering resolution.
3. If no resolution is provided in the coordinate files, then use the [full_resolution](https://github.com/YuelongWu/feabas/blob/1ee3208d7eb6d2c4a32f641135a70b6d64aa1edf/configs/general_configs.yaml#L4) in general settings.

This change involved several files, and I tested a few cases on my machine that seemed to be working (except for some new issues with TensorsorStore when downsampling, so I temporarily limited its version). But let me know if you notice any issues or think this is not making sense.
